[package]
name = "heightmap"
version = "0.3.8"
authors = ["Meshiest <meek.mesh@gmail.com>"]
edition = "2018"

[dependencies]
brs = "0.2.0"
image = "0.23.4"
clap = "2.33.0"
byteorder = "1.3.4"
